name: Test upstream downlaod

on:
  schedule:
  - cron: '0 * * * *'

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test-upstream:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Clean install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Override dist with build
        run: |
          rm -rf dist
          mv build dist

      - name: Run action
        uses: ./
        with:
          shiroa-version: latest
          allow-prereleases: true

      - name: Run `tt --version`
        run: tt --version
